channels:
  - conda-forge
  - conda 
  - pytorch
  - pypi
dependencies:
  - r-base=4
  - r-essentials
  - r-tensorflow
  - r-keras
  - r-boot
  - r-caret
  - r-learnr
  - r-rstan
  - r-brms
  - r-mlr
  - r-superlearner
  - r-caret
  - python                          
  - pip